services:
  - type: web
    rootDir: lifeos
    env: python
    plan: free
    rootDir: lifeos
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
